spring:
  profiles.active: dev
server.port: 1210
artifact:
  id : TrafficDemo
  version: 0.0.1-SNAPSHOT
environment:
  nodeName :
---
spring:
  profiles: dev
application:
  decryptionKey: sensDemo
mongodb: 
  host: localhost
  port: 27017
  database: sensDb
  #username: userSens
  #password: lSS9D8MdHb6X27mxoMC80GaFt+Ilry2H
  #authenticationDB: sensDb